name: Release

on:
  push:
    tags:
    - v*

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with: # Required: the version of golangci-lint is required and must be specified without a patch version:
        # we always use the latest patch version.
        version: v1.52
        # Optional: if set to `true` then the all caching functionality will be complete disabled,
        #           takes precedence over all other caching options.
        skip-cache: true
        args: --issues-exit-code=1
        only-new-issues: true

    - name: Run gofmt
      run: diff -u <(echo -n) <(gofmt -d .)

    - name: Test
      run: go test -timeout=120s -v -race -short

    - name: Import GPG key
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v4
      with:
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
